### PR TITLE
Port from libintl to intl.

### PR DESCRIPTION
**Pull request by Sineaggi**
Part of a move towards using upstream solution files is moving from libintl to intl. As such I've changed almost all instances of libintl to intl as preparation.

### CODE REVIEW

**Comment by Sineaggi** [comment]
Please test this, although it worked on my machine, it may not work for everyone.

**Comment by Sineaggi** [comment]
Hm? What do you mean?

**Comment by nacho** [comment]
The new patch that u r applying is not added to the repo?

**Comment by Sineaggi** [comment]
Should be visible here https://github.com/nice-software/gtk-win32/pull/15/files#diff-9d30f08ce2fba79380e66b096778eb97

**Comment by nacho** [comment]
Missed that thanks. I'll give it a try one of these days. If there is something wrong I'll reopen this.

**Comment by nacho** [comment]
FYI I also started to write this: https://github.com/nacho/icbuild
It is a rewrite of the whole thing using python based on jhbuild. If you feel like helping would be great

**Comment by nacho** [comment]
Hey,

I just tested this and I get the next error:
gettext-runtime : Started
gettext-runtime : patching file gettext-runtime/intl/intl.def
gettext-runtime : can't find file to patch at input line 4
gettext-runtime : Perhaps you used the wrong -p or --strip option?
gettext-runtime : The text leading up to this was:
gettext-runtime : --------------------------
gettext-runtime : |diff -Naur /c/Users/Clayton/Desktop/difffs/gettext-orig/gettext-runtime/intl/CMakeLists.txt /c/Users/
Clayton/Desktop/difffs/gettext-mod/gettext-runtime/intl/CMakeLists.txt
gettext-runtime : |--- /c/Users/Clayton/Desktop/difffs/gettext-orig/gettext-runtime/intl/CMakeLists.txt 2012-01-21 21:10
:25.000000000 -0700
gettext-runtime : |+++ /c/Users/Clayton/Desktop/difffs/gettext-mod/gettext-runtime/intl/CMakeLists.txt  2015-12-02 16:23
:51.903960200 -0700
gettext-runtime : --------------------------
gettext-runtime : File to patch:
gettext-runtime : Skip this patch? [y]
gettext-runtime : Skipping patch.
gettext-runtime : 1 out of 1 hunk ignored
gettext-runtime : C:\msys64\usr\bin\patch.exe -p1 -i gettext-lib-prexif.patch exited with code 1
gettext-runtime : Failed

The following items were successfully built:
win-iconv

The following items failed to build:
gettext-runtime

**Comment by nacho** [comment]
So it was a problem on the patch, it should be fixed now in: https://github.com/wingtk/gtk-win32/commit/caab17cd44c89ff7cf11d1281e45ef5ba82a9920

**Pull request merged**
